db:
  mem_limit: 1024m
  image: mysql
  ports:
   - "3306:3306"
  volumes:
    - /home/mysql:/var/lib/mysql
    - /home/mysql:/var/lib/db
  environment:
    MYSQL_ROOT_PASSWORD: password
redis:
  command: ["redis-server", "-p", "6379"]
  mem_limit: 1024m
  image: redis
  labels:
    product: esell
    environment: staging
  ports:
   - "6379:6379"
  volumes_from:
    - db
app:
  mem_limit: 2g
  image: testapp
  command: "testapp -v debug"
  ports:
    - "3000:3000"
    - "3000:3000/udp"
  links:
    - db:db
    - redis:redis
  environment:
   REDIS_URL: redis://redis:6379/0
   DB_URL: db:3306
