db:
  mem_limit: 20g
  image: mysql
  ports:
   - "3306:3306"
  volumes:
    - /home/mysql:/var/lib/mysql
    - /home/mysql:/var/lib/db
  environment:
    MYSQL_ROOT_PASSWORD: password
redis:
  mem_limit: 20g
  ports:
   - "6379:6379"
app:
  mem_limit: 20g
  image: testapp
  command: "testapp"
  ports:
    - "3000:3000"
  links:
    - db:db
    - redis:redis
  environment:
   REDIS_URL: redis://redis:6379/0
   DB_URL: db:3306
